spring:
  application:
    name: sping_mybatis_demo02
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis_study
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 205148
mybatis:
  configuration:
    #日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启驼峰原则映射开关
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml